# Generated by Django 5.2.8 on 2025-11-28 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course'),
        ),
    ]
